#!/usr/bin/fish 

if test (count $argv) -eq 4 -a $argv[1]="makemodel"
    python -c '''import Shaker.rna_tools.rna_io as r; import Shaker.simushape as s;
print "zomg"
    '''

else if test (count $argv) -eq 4
    echo "4 argv"
else
    echo  '''
    I am displaying this help-message becuase your parameters are bad

    USAGE:
    1. train a model:
    shaker  makemodel react-file dbn-file output-model-file

    2. use a model:
    shaker predict model sequence
    '''

end 



import sys
import ShaKer.rna_tools.rna_io as rio
import ShaKer.simushape as sim

if  sys.argv[1]  == "makemodel" and len(sys.argv==5):
    data = rio.get_all_data(sys.argv[2],sys.argv[3])
    model  = sim.make_model(data,data.keys())
    with open(sys.argv[3], 'wb') as file:
        pickle.dump(model, file)

elif  sys.argv[1]  == "predict" and len(sys.argv)==4:
    with open(sys.argv[2], 'rb') as file:
        model = pickle.load(file)
    print (sim.predict(model,sys.argv[3]))
else:
    print '''
    I am displaying this help-message becuase your parameters are bad

    USAGE:
    1. train a model:
    python shaker.py makemodel react-file dbn-file output-model-file

    2. use a model:
    python shaker.py predict model sequence
    '''

